name: dnd_app
description: D&D Campaign Shop mobile app (Android)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  collection: ^1.19.0
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.2
  go_router: ^17.1.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.10.0
  package_info_plus: ^8.3.1
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
